const ADD_TODO = "ADD_TODO";
const EDIT_TODO = "EDIT_TODO";
const DELETE_TODO = "DELETE_TODO";
const MARK_COMPLETED = "MARK_COMPLETED";
const SET_TIME = "SET_TIME";

export { ADD_TODO, EDIT_TODO, DELETE_TODO, MARK_COMPLETED, SET_TIME};